apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: {{ .Values.nodePort }}
  selector:
    app: wordpress
    tier: frontend
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
spec:
  ports:
    - port: {{ .Values.mySqlPort }}

  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
