apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: {{ .Values.wordpressReplicaCount }}
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: wordpress
          image: wordpress:5-php7.1-apache
          ports:
          - containerPort: 80
            name: wordpress
          volumeMounts:
            - name: wp-persist-storage
              mountPath: /var/www
          env:
          - name: WORDPRESS_DB_HOST
            value: wordpress-mysql
          - name: WORDPRESS_DB_PASSWORD
            value: polyconseil #{{ .Values.mySqlPassword }} Helm seems to handle secrets differently, to investigate further
            ####This is the best way of doing it but there is a problem and I can't find it and I don't have time!!!
            # valueFrom:
            #  secretKeyRef:
            #    name: wp-db-secrets
            #    key: MYSQL_ROOT_PASSWORD
                #- name: WORDPRESS_DB_USER
                #value: root
                # - name: WORDPRESS_DB_NAME
                #value: wordpress
      volumes:
        - name: wp-persist-storage
          persistentVolumeClaim:
                  claimName: wp-pv-claim
